name: Build and Cache with Cachix

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 0 * * 0' # Runs every Sunday at 00:15
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31

      - name: Authenticate with Cachix
        uses: cachix/cachix-action@v15
        with:
          name: larstvei
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and Push with Cachix
        run: |
          set -e
          nix develop
          nix build --json | jq -r '.[].outputs | to_entries[].value' | cachix push larstvei
